import type { Metadata } from 'next'
import { ThemeProvider } from 'next-themes'

import './globals.css'

import { Sidebar } from '@/components/Sidebar'
import { SwitchTheme } from '@/components/SwitchTheme'

export const metadata: Metadata = {
  title: 'Tailwind Next',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class">
          <div className="relative min-h-screen lg:grid lg:grid-cols-app dark:bg-zinc-900">
            <Sidebar />

            <main className="max-w-screen px-4 pb-12 pt-24 lg:col-start-2 lg:w-auto lg:px-8 lg:pt-8">
              {children}
            </main>

            <SwitchTheme />
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
